version: "3.9"
networks:
  cassandra-net:
services:
  cass1:
    image: ${CAS_IMAGE}
    container_name: cass1
    hostname: cass1
    networks:
      - cassandra-net
    ports:
      - "9042:9042"
    volumes:
      - ./test.sh:/test.sh
    environment: &environment
        CASSANDRA_SEEDS: "cass1,cass2,cass3"
        CASSANDRA_CLUSTER_NAME: SolarSystem
        CASSANDRA_DC: Mars
        CASSANDRA_RACK: West
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
        CASSANDRA_NUM_TOKENS: 128
        CASSANDRA_CONFIG: /etc/cassandra/
        CAS_CONS: ${CAS_CONS}

  cass2:
    image: ${CAS_IMAGE}
    container_name: cass2
    hostname: cass2
    networks:
      - cassandra-net
    ports:
      - "9043:9042"
    volumes:
      - ./test.sh:/test.sh
    environment: *environment

  cass3:
    image: ${CAS_IMAGE}
    container_name: cass3
    hostname: cass3
    networks:
      - cassandra-net
    ports:
      - "9044:9042"
    volumes:
      - ./test.sh:/test.sh
    environment: *environment
